plat: mt8365

optee:
  board: mt8175
  flags: CFG_ARM64_core=y ta-targets=ta_arm64 CFG_DRAM_SIZE=0x80000000 CFG_CORE_HEAP_SIZE=131072

uboot:
  spl_defconfig: mt8365_pumpkin_android_spl_defconfig
  defconfig: mt8365_pumpkin_android_defconfig

android:
  binaries_path: device/mediatek/boards-binaries/i350_sb35
