mtk_boot:
  ddr_size_max: 122880 # 120 Ko
  spl_size_max: 133120 # 130 Ko

ddr_loader:
  plat: mt8365

libatf:
  plat: mt8365

libbase:
  plat: mt8365

bl31:
  plat: mt8365

optee:
  plat: mt8175
  flags: CFG_ARM64_core=y ta-targets=ta_arm64 CFG_DRAM_SIZE=0xc0000000 CFG_CORE_HEAP_SIZE=131072

uboot:
  plat: mt8365
  defconfig: mt8365_evk_defconfig

android:
  binaries_path: device/mediatek/boards-binaries/i350_evk

secure:
  plat: mt8365
