plat: mt8183

mmcboot:
  ddr_size_max: 143360 # 140 Ko
  spl_size_max: 368640 # 360 Ko

optee:
  flags: CFG_ARM64_core=y ta-targets=ta_arm64 CFG_DRAM_SIZE=0x80000000 CFG_CORE_HEAP_SIZE=131072

uboot:
  spl_defconfig: mt8183_pumpkin_android_spl_defconfig
  defconfig: mt8183_pumpkin_android_defconfig

android:
  binaries_path: device/mediatek/boards-binaries/i500_pumpkin
